# Generated by Django 3.2 on 2023-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_from', models.TextField(verbose_name='From')),
                ('street_to', models.TextField(verbose_name='To')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Boocked trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
