# Generated by Django 3.2 on 2023-02-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresfield', '0003_auto_20230216_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='street_from',
            field=models.TextField(max_length=70, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='street_to',
            field=models.TextField(max_length=70, verbose_name='To'),
        ),
    ]
