# Generated by Django 3.2 on 2023-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresfield', '0004_auto_20230216_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='phone',
            field=models.IntegerField(max_length=27, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='street_from',
            field=models.CharField(max_length=70, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='street_to',
            field=models.CharField(max_length=70, verbose_name='To'),
        ),
    ]
