# Generated by Django 3.2 on 2023-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresfield', '0005_auto_20230216_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
    ]
